# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AdjustStyle
                                 A QGIS plugin
 Adjust color, line thickness, font size etc. of all symbols/labels.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-05
        copyright            : (C) 2023 by Florian Neukirchen
        email                : mail@riannek.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AdjustStyle class from file AdjustStyle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .adjust_style import AdjustStyle
    return AdjustStyle(iface)
